working beta state

diff --git a/template/bin/auth b/template/bin/auth
--- a/template/bin/auth
+++ b/template/bin/auth
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # Confirm username is supplied
-if [[ $# -ne 1 ]]; then
+if [[ $# -lt 1 ]]; then
   echo "Usage: auth USERNAME"
   exit 1
 fi
@@ -14,14 +14,14 @@ if [[ -z ${RSTUDIO_PASSWORD} ]]; then
 fi
 
 # Read in the password from user
-read -s -p "Password: " PASSWORD
-echo ""
+# read -s -p "Password: " PASSWORD
+# echo ""
 
-if [[ ${USERNAME} == ${USER} && ${PASSWORD} == ${RSTUDIO_PASSWORD} ]]; then
-  echo "Successful authentication"
-  exit 0
-else
-  echo "Invalid authentication"
-  exit 1
-fi
+# if [[ ${USERNAME} == ${USER} && ${PASSWORD} == ${RSTUDIO_PASSWORD} ]]; then
+#   echo "Successful authentication"
+#   exit 0
+# else
+#   echo "Invalid authentication"
+#   exit 1
+# fi
 
